apiVersion: v1
kind: Pod
metadata:
  name: fortune-env
spec:
  containers:
    - image: luksa/fortune:env
      name: html-generator
      env:
        - name: INTERVAL
          value: "30"
      volumeMounts:
        - mountPath: /var/htdocs
          name: html

    - image: nginx:alpine
      name: web-server
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: html
          readOnly: true
      ports:
        - containerPort: 80
          protocol: TCP

  volumes:
    - name: html
      emptyDir: {}

