apiVersion: batch/v1
kind: Job
metadata:
  name: multi-completion-batch-job
spec:
  backoffLimit: 10 # How many times the job failed.
  activeDeadlineSeconds: 36000 # How many seconds before timeout
  completions: 5
  parallelism: 2
  template:
    metadata:
      labels:
        app: batch-job
    spec:
      restartPolicy: OnFailure
      containers:
        - name: main
          image: luksa/batch-job
